version: '3.8'

services:
  link-shortener:
    image: gchr.io/gigirassy/kurl-link:main
    container_name: link-shortener
    ports:
      - "3000:3000"
    environment:
      - CREATE_PASSWORD=HUNTER7 #change me!
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "100M"
